name: CI/CD Pipeline

on:
  push:
    paths:
      - 'index.html'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/my-nginx:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/my-nginx:latest

    - name: Deploy with Docker Compose
      run:
        docker-compose -f /path/to/your/docker-compose.yml up -d
